// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1WorkflowLintRequest io argoproj workflow v1alpha1 workflow lint request
//
// swagger:model io.argoproj.workflow.v1alpha1.WorkflowLintRequest
type IoArgoprojWorkflowV1alpha1WorkflowLintRequest struct {

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// workflow
	Workflow *IoArgoprojWorkflowV1alpha1Workflow `json:"workflow,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 workflow lint request
func (m *IoArgoprojWorkflowV1alpha1WorkflowLintRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateWorkflow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1WorkflowLintRequest) validateWorkflow(formats strfmt.Registry) error {
	if swag.IsZero(m.Workflow) { // not required
		return nil
	}

	if m.Workflow != nil {
		if err := m.Workflow.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workflow")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 workflow lint request based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1WorkflowLintRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateWorkflow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1WorkflowLintRequest) contextValidateWorkflow(ctx context.Context, formats strfmt.Registry) error {

	if m.Workflow != nil {
		if err := m.Workflow.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workflow")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowLintRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowLintRequest) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1WorkflowLintRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
