// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1MutexStatus MutexStatus contains which objects hold  mutex locks, and which objects this workflow is waiting on to release locks.
//
// swagger:model io.argoproj.workflow.v1alpha1.MutexStatus
type IoArgoprojWorkflowV1alpha1MutexStatus struct {

	// Holding is a list of mutexes and their respective objects that are held by mutex lock for this io.argoproj.workflow.v1alpha1.
	Holding []*IoArgoprojWorkflowV1alpha1MutexHolding `json:"holding"`

	// Waiting is a list of mutexes and their respective objects this workflow is waiting for.
	Waiting []*IoArgoprojWorkflowV1alpha1MutexHolding `json:"waiting"`
}

// Validate validates this io argoproj workflow v1alpha1 mutex status
func (m *IoArgoprojWorkflowV1alpha1MutexStatus) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateHolding(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWaiting(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1MutexStatus) validateHolding(formats strfmt.Registry) error {
	if swag.IsZero(m.Holding) { // not required
		return nil
	}

	for i := 0; i < len(m.Holding); i++ {
		if swag.IsZero(m.Holding[i]) { // not required
			continue
		}

		if m.Holding[i] != nil {
			if err := m.Holding[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("holding" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1MutexStatus) validateWaiting(formats strfmt.Registry) error {
	if swag.IsZero(m.Waiting) { // not required
		return nil
	}

	for i := 0; i < len(m.Waiting); i++ {
		if swag.IsZero(m.Waiting[i]) { // not required
			continue
		}

		if m.Waiting[i] != nil {
			if err := m.Waiting[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("waiting" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 mutex status based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1MutexStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateHolding(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWaiting(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1MutexStatus) contextValidateHolding(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Holding); i++ {

		if m.Holding[i] != nil {
			if err := m.Holding[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("holding" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1MutexStatus) contextValidateWaiting(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Waiting); i++ {

		if m.Waiting[i] != nil {
			if err := m.Waiting[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("waiting" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1MutexStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1MutexStatus) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1MutexStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
