// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest io argoproj workflow v1alpha1 lint cron workflow request
//
// swagger:model io.argoproj.workflow.v1alpha1.LintCronWorkflowRequest
type IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest struct {

	// cron workflow
	CronWorkflow *IoArgoprojWorkflowV1alpha1CronWorkflow `json:"cronWorkflow,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 lint cron workflow request
func (m *IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCronWorkflow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest) validateCronWorkflow(formats strfmt.Registry) error {
	if swag.IsZero(m.CronWorkflow) { // not required
		return nil
	}

	if m.CronWorkflow != nil {
		if err := m.CronWorkflow.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cronWorkflow")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 lint cron workflow request based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCronWorkflow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest) contextValidateCronWorkflow(ctx context.Context, formats strfmt.Registry) error {

	if m.CronWorkflow != nil {
		if err := m.CronWorkflow.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("cronWorkflow")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1LintCronWorkflowRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
