// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1Synchronization Synchronization holds synchronization lock configuration
//
// swagger:model io.argoproj.workflow.v1alpha1.Synchronization
type IoArgoprojWorkflowV1alpha1Synchronization struct {

	// Mutex holds the Mutex lock details
	Mutex *IoArgoprojWorkflowV1alpha1Mutex `json:"mutex,omitempty"`

	// Semaphore holds the Semaphore configuration
	Semaphore *IoArgoprojWorkflowV1alpha1SemaphoreRef `json:"semaphore,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 synchronization
func (m *IoArgoprojWorkflowV1alpha1Synchronization) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateMutex(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSemaphore(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Synchronization) validateMutex(formats strfmt.Registry) error {
	if swag.IsZero(m.Mutex) { // not required
		return nil
	}

	if m.Mutex != nil {
		if err := m.Mutex.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mutex")
			}
			return err
		}
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Synchronization) validateSemaphore(formats strfmt.Registry) error {
	if swag.IsZero(m.Semaphore) { // not required
		return nil
	}

	if m.Semaphore != nil {
		if err := m.Semaphore.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("semaphore")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 synchronization based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1Synchronization) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateMutex(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSemaphore(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Synchronization) contextValidateMutex(ctx context.Context, formats strfmt.Registry) error {

	if m.Mutex != nil {
		if err := m.Mutex.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("mutex")
			}
			return err
		}
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Synchronization) contextValidateSemaphore(ctx context.Context, formats strfmt.Registry) error {

	if m.Semaphore != nil {
		if err := m.Semaphore.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("semaphore")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Synchronization) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Synchronization) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1Synchronization
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
