// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoArgoprojWorkflowV1alpha1WorkflowTemplateDeleteResponse io argoproj workflow v1alpha1 workflow template delete response
//
// swagger:model io.argoproj.workflow.v1alpha1.WorkflowTemplateDeleteResponse
type IoArgoprojWorkflowV1alpha1WorkflowTemplateDeleteResponse interface{}
