// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest io argoproj workflow v1alpha1 workflow resubmit request
//
// swagger:model io.argoproj.workflow.v1alpha1.WorkflowResubmitRequest
type IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest struct {

	// memoized
	Memoized bool `json:"memoized,omitempty"`

	// name
	Name string `json:"name,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 workflow resubmit request
func (m *IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 workflow resubmit request based on context it is used
func (m *IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1WorkflowResubmitRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
