// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1WorkflowTemplateRef WorkflowTemplateRef is a reference to a WorkflowTemplate resource.
//
// swagger:model io.argoproj.workflow.v1alpha1.WorkflowTemplateRef
type IoArgoprojWorkflowV1alpha1WorkflowTemplateRef struct {

	// ClusterScope indicates the referred template is cluster scoped (i.e. a ClusterWorkflowTemplate).
	ClusterScope bool `json:"clusterScope,omitempty"`

	// Name is the resource name of the workflow template.
	Name string `json:"name,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 workflow template ref
func (m *IoArgoprojWorkflowV1alpha1WorkflowTemplateRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 workflow template ref based on context it is used
func (m *IoArgoprojWorkflowV1alpha1WorkflowTemplateRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowTemplateRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowTemplateRef) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1WorkflowTemplateRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
