// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1TarStrategy TarStrategy will tar and gzip the file or directory when saving
//
// swagger:model io.argoproj.workflow.v1alpha1.TarStrategy
type IoArgoprojWorkflowV1alpha1TarStrategy struct {

	// CompressionLevel specifies the gzip compression level to use for the artifact. Defaults to gzip.DefaultCompression.
	CompressionLevel int32 `json:"compressionLevel,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 tar strategy
func (m *IoArgoprojWorkflowV1alpha1TarStrategy) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 tar strategy based on context it is used
func (m *IoArgoprojWorkflowV1alpha1TarStrategy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1TarStrategy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1TarStrategy) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1TarStrategy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
