// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1GetUserInfoResponse io argoproj workflow v1alpha1 get user info response
//
// swagger:model io.argoproj.workflow.v1alpha1.GetUserInfoResponse
type IoArgoprojWorkflowV1alpha1GetUserInfoResponse struct {

	// issuer
	Issuer string `json:"issuer,omitempty"`

	// subject
	Subject string `json:"subject,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 get user info response
func (m *IoArgoprojWorkflowV1alpha1GetUserInfoResponse) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 get user info response based on context it is used
func (m *IoArgoprojWorkflowV1alpha1GetUserInfoResponse) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1GetUserInfoResponse) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1GetUserInfoResponse) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1GetUserInfoResponse
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
