// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1ExecutorConfig ExecutorConfig holds configurations of an executor container.
//
// swagger:model io.argoproj.workflow.v1alpha1.ExecutorConfig
type IoArgoprojWorkflowV1alpha1ExecutorConfig struct {

	// ServiceAccountName specifies the service account name of the executor container.
	ServiceAccountName string `json:"serviceAccountName,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 executor config
func (m *IoArgoprojWorkflowV1alpha1ExecutorConfig) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 executor config based on context it is used
func (m *IoArgoprojWorkflowV1alpha1ExecutorConfig) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ExecutorConfig) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ExecutorConfig) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1ExecutorConfig
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
