// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoArgoprojWorkflowV1alpha1SuppliedValueFrom SuppliedValueFrom is a placeholder for a value to be filled in directly, either through the CLI, API, etc.
//
// swagger:model io.argoproj.workflow.v1alpha1.SuppliedValueFrom
type IoArgoprojWorkflowV1alpha1SuppliedValueFrom interface{}
