// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1ArchiveStrategy ArchiveStrategy describes how to archive files/directory when saving artifacts
//
// swagger:model io.argoproj.workflow.v1alpha1.ArchiveStrategy
type IoArgoprojWorkflowV1alpha1ArchiveStrategy struct {

	// none
	None IoArgoprojWorkflowV1alpha1NoneStrategy `json:"none,omitempty"`

	// tar
	Tar *IoArgoprojWorkflowV1alpha1TarStrategy `json:"tar,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 archive strategy
func (m *IoArgoprojWorkflowV1alpha1ArchiveStrategy) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateTar(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1ArchiveStrategy) validateTar(formats strfmt.Registry) error {
	if swag.IsZero(m.Tar) { // not required
		return nil
	}

	if m.Tar != nil {
		if err := m.Tar.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tar")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 archive strategy based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1ArchiveStrategy) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateTar(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1ArchiveStrategy) contextValidateTar(ctx context.Context, formats strfmt.Registry) error {

	if m.Tar != nil {
		if err := m.Tar.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("tar")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ArchiveStrategy) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ArchiveStrategy) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1ArchiveStrategy
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
