// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1Mutex Mutex holds Mutex configuration
//
// swagger:model io.argoproj.workflow.v1alpha1.Mutex
type IoArgoprojWorkflowV1alpha1Mutex struct {

	// name of the mutex
	Name string `json:"name,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 mutex
func (m *IoArgoprojWorkflowV1alpha1Mutex) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 mutex based on context it is used
func (m *IoArgoprojWorkflowV1alpha1Mutex) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Mutex) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Mutex) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1Mutex
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
