// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
)

// IoArgoprojWorkflowV1alpha1Amount Amount represent a numeric amount.
//
// swagger:model io.argoproj.workflow.v1alpha1.Amount
type IoArgoprojWorkflowV1alpha1Amount float64

// Validate validates this io argoproj workflow v1alpha1 amount
func (m IoArgoprojWorkflowV1alpha1Amount) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 amount based on context it is used
func (m IoArgoprojWorkflowV1alpha1Amount) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}
