// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1WorkflowCreateRequest io argoproj workflow v1alpha1 workflow create request
//
// swagger:model io.argoproj.workflow.v1alpha1.WorkflowCreateRequest
type IoArgoprojWorkflowV1alpha1WorkflowCreateRequest struct {

	// create options
	CreateOptions *IoK8sApimachineryPkgApisMetaV1CreateOptions `json:"createOptions,omitempty"`

	// This field is no longer used.
	InstanceID string `json:"instanceID,omitempty"`

	// namespace
	Namespace string `json:"namespace,omitempty"`

	// server dry run
	ServerDryRun bool `json:"serverDryRun,omitempty"`

	// workflow
	Workflow *IoArgoprojWorkflowV1alpha1Workflow `json:"workflow,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 workflow create request
func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateCreateOptions(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateWorkflow(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) validateCreateOptions(formats strfmt.Registry) error {
	if swag.IsZero(m.CreateOptions) { // not required
		return nil
	}

	if m.CreateOptions != nil {
		if err := m.CreateOptions.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createOptions")
			}
			return err
		}
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) validateWorkflow(formats strfmt.Registry) error {
	if swag.IsZero(m.Workflow) { // not required
		return nil
	}

	if m.Workflow != nil {
		if err := m.Workflow.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workflow")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 workflow create request based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateCreateOptions(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateWorkflow(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) contextValidateCreateOptions(ctx context.Context, formats strfmt.Registry) error {

	if m.CreateOptions != nil {
		if err := m.CreateOptions.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("createOptions")
			}
			return err
		}
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) contextValidateWorkflow(ctx context.Context, formats strfmt.Registry) error {

	if m.Workflow != nil {
		if err := m.Workflow.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("workflow")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1WorkflowCreateRequest) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1WorkflowCreateRequest
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
