// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoArgoprojWorkflowV1alpha1OSSArtifact OSSArtifact is the location of an Alibaba Cloud OSS artifact
//
// swagger:model io.argoproj.workflow.v1alpha1.OSSArtifact
type IoArgoprojWorkflowV1alpha1OSSArtifact struct {

	// AccessKeySecret is the secret selector to the bucket's access key
	// Required: true
	AccessKeySecret *IoK8sAPICoreV1SecretKeySelector `json:"accessKeySecret"`

	// Bucket is the name of the bucket
	// Required: true
	Bucket *string `json:"bucket"`

	// Endpoint is the hostname of the bucket endpoint
	// Required: true
	Endpoint *string `json:"endpoint"`

	// Key is the path in the bucket where the artifact resides
	// Required: true
	Key *string `json:"key"`

	// SecretKeySecret is the secret selector to the bucket's secret key
	// Required: true
	SecretKeySecret *IoK8sAPICoreV1SecretKeySelector `json:"secretKeySecret"`
}

// Validate validates this io argoproj workflow v1alpha1 o s s artifact
func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateAccessKeySecret(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateBucket(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateKey(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSecretKeySecret(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) validateAccessKeySecret(formats strfmt.Registry) error {

	if err := validate.Required("accessKeySecret", "body", m.AccessKeySecret); err != nil {
		return err
	}

	if m.AccessKeySecret != nil {
		if err := m.AccessKeySecret.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("accessKeySecret")
			}
			return err
		}
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) validateBucket(formats strfmt.Registry) error {

	if err := validate.Required("bucket", "body", m.Bucket); err != nil {
		return err
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) validateEndpoint(formats strfmt.Registry) error {

	if err := validate.Required("endpoint", "body", m.Endpoint); err != nil {
		return err
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) validateKey(formats strfmt.Registry) error {

	if err := validate.Required("key", "body", m.Key); err != nil {
		return err
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) validateSecretKeySecret(formats strfmt.Registry) error {

	if err := validate.Required("secretKeySecret", "body", m.SecretKeySecret); err != nil {
		return err
	}

	if m.SecretKeySecret != nil {
		if err := m.SecretKeySecret.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("secretKeySecret")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 o s s artifact based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateAccessKeySecret(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := m.contextValidateSecretKeySecret(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) contextValidateAccessKeySecret(ctx context.Context, formats strfmt.Registry) error {

	if m.AccessKeySecret != nil {
		if err := m.AccessKeySecret.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("accessKeySecret")
			}
			return err
		}
	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) contextValidateSecretKeySecret(ctx context.Context, formats strfmt.Registry) error {

	if m.SecretKeySecret != nil {
		if err := m.SecretKeySecret.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("secretKeySecret")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1OSSArtifact) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1OSSArtifact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
