// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoArgoprojWorkflowV1alpha1Item Item expands a single workflow step into multiple parallel steps The value of Item can be a map, string, bool, or number
//
// swagger:model io.argoproj.workflow.v1alpha1.Item
type IoArgoprojWorkflowV1alpha1Item interface{}
