// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef io argoproj workflow v1alpha1 artifact repository ref
//
// swagger:model io.argoproj.workflow.v1alpha1.ArtifactRepositoryRef
type IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef struct {

	// config map
	ConfigMap string `json:"configMap,omitempty"`

	// key
	Key string `json:"key,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 artifact repository ref
func (m *IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 artifact repository ref based on context it is used
func (m *IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1ArtifactRepositoryRef
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
