// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoArgoprojWorkflowV1alpha1Metrics Metrics are a list of metrics emitted from a Workflow/Template
//
// swagger:model io.argoproj.workflow.v1alpha1.Metrics
type IoArgoprojWorkflowV1alpha1Metrics struct {

	// Prometheus is a list of prometheus metrics to be emitted
	// Required: true
	Prometheus []*IoArgoprojWorkflowV1alpha1Prometheus `json:"prometheus"`
}

// Validate validates this io argoproj workflow v1alpha1 metrics
func (m *IoArgoprojWorkflowV1alpha1Metrics) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validatePrometheus(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Metrics) validatePrometheus(formats strfmt.Registry) error {

	if err := validate.Required("prometheus", "body", m.Prometheus); err != nil {
		return err
	}

	for i := 0; i < len(m.Prometheus); i++ {
		if swag.IsZero(m.Prometheus[i]) { // not required
			continue
		}

		if m.Prometheus[i] != nil {
			if err := m.Prometheus[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("prometheus" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 metrics based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1Metrics) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidatePrometheus(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Metrics) contextValidatePrometheus(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Prometheus); i++ {

		if m.Prometheus[i] != nil {
			if err := m.Prometheus[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("prometheus" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Metrics) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Metrics) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1Metrics
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
