// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1PodGC PodGC describes how to delete completed pods as they complete
//
// swagger:model io.argoproj.workflow.v1alpha1.PodGC
type IoArgoprojWorkflowV1alpha1PodGC struct {

	// Strategy is the strategy to use. One of "OnPodCompletion", "OnPodSuccess", "OnWorkflowCompletion", "OnWorkflowSuccess"
	Strategy string `json:"strategy,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 pod g c
func (m *IoArgoprojWorkflowV1alpha1PodGC) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 pod g c based on context it is used
func (m *IoArgoprojWorkflowV1alpha1PodGC) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1PodGC) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1PodGC) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1PodGC
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
