// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1ValueFrom ValueFrom describes a location in which to obtain the value to a parameter
//
// swagger:model io.argoproj.workflow.v1alpha1.ValueFrom
type IoArgoprojWorkflowV1alpha1ValueFrom struct {

	// Default specifies a value to be used if retrieving the value from the specified source fails
	Default string `json:"default,omitempty"`

	// Selector (https://github.com/antonmedv/expr) that is evaluated against the event to get the value of the parameter. E.g. `payload.message`
	Event string `json:"event,omitempty"`

	// JQFilter expression against the resource object in resource templates
	JqFilter string `json:"jqFilter,omitempty"`

	// JSONPath of a resource to retrieve an output parameter value from in resource templates
	JSONPath string `json:"jsonPath,omitempty"`

	// Parameter reference to a step or dag task in which to retrieve an output parameter value from (e.g. '{{steps.mystep.outputs.myparam}}')
	Parameter string `json:"parameter,omitempty"`

	// Path in the container to retrieve an output parameter value from in container templates
	Path string `json:"path,omitempty"`

	// Supplied value to be filled in directly, either through the CLI, API, etc.
	Supplied IoArgoprojWorkflowV1alpha1SuppliedValueFrom `json:"supplied,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 value from
func (m *IoArgoprojWorkflowV1alpha1ValueFrom) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 value from based on context it is used
func (m *IoArgoprojWorkflowV1alpha1ValueFrom) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ValueFrom) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1ValueFrom) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1ValueFrom
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
