// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoArgoprojWorkflowV1alpha1NodeSynchronizationStatus NodeSynchronizationStatus stores the status of a node
//
// swagger:model io.argoproj.workflow.v1alpha1.NodeSynchronizationStatus
type IoArgoprojWorkflowV1alpha1NodeSynchronizationStatus struct {

	// Waiting is the name of the lock that this node is waiting for
	Waiting string `json:"waiting,omitempty"`
}

// Validate validates this io argoproj workflow v1alpha1 node synchronization status
func (m *IoArgoprojWorkflowV1alpha1NodeSynchronizationStatus) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 node synchronization status based on context it is used
func (m *IoArgoprojWorkflowV1alpha1NodeSynchronizationStatus) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1NodeSynchronizationStatus) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1NodeSynchronizationStatus) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1NodeSynchronizationStatus
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
