// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoArgoprojWorkflowV1alpha1Histogram Histogram is a Histogram prometheus metric
//
// swagger:model io.argoproj.workflow.v1alpha1.Histogram
type IoArgoprojWorkflowV1alpha1Histogram struct {

	// Buckets is a list of bucket divisors for the histogram
	// Required: true
	Buckets []IoArgoprojWorkflowV1alpha1Amount `json:"buckets"`

	// Value is the value of the metric
	// Required: true
	Value *string `json:"value"`
}

// Validate validates this io argoproj workflow v1alpha1 histogram
func (m *IoArgoprojWorkflowV1alpha1Histogram) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateBuckets(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateValue(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Histogram) validateBuckets(formats strfmt.Registry) error {

	if err := validate.Required("buckets", "body", m.Buckets); err != nil {
		return err
	}

	for i := 0; i < len(m.Buckets); i++ {

		if err := m.Buckets[i].Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buckets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Histogram) validateValue(formats strfmt.Registry) error {

	if err := validate.Required("value", "body", m.Value); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this io argoproj workflow v1alpha1 histogram based on the context it is used
func (m *IoArgoprojWorkflowV1alpha1Histogram) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateBuckets(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1Histogram) contextValidateBuckets(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(m.Buckets); i++ {

		if err := m.Buckets[i].ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("buckets" + "." + strconv.Itoa(i))
			}
			return err
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Histogram) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1Histogram) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1Histogram
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
