// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// IoArgoprojWorkflowV1alpha1RawArtifact RawArtifact allows raw string content to be placed as an artifact in a container
//
// swagger:model io.argoproj.workflow.v1alpha1.RawArtifact
type IoArgoprojWorkflowV1alpha1RawArtifact struct {

	// Data is the string contents of the artifact
	// Required: true
	Data *string `json:"data"`
}

// Validate validates this io argoproj workflow v1alpha1 raw artifact
func (m *IoArgoprojWorkflowV1alpha1RawArtifact) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateData(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *IoArgoprojWorkflowV1alpha1RawArtifact) validateData(formats strfmt.Registry) error {

	if err := validate.Required("data", "body", m.Data); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this io argoproj workflow v1alpha1 raw artifact based on context it is used
func (m *IoArgoprojWorkflowV1alpha1RawArtifact) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1RawArtifact) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoArgoprojWorkflowV1alpha1RawArtifact) UnmarshalBinary(b []byte) error {
	var res IoArgoprojWorkflowV1alpha1RawArtifact
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
