// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoArgoprojWorkflowV1alpha1NoneStrategy NoneStrategy indicates to skip tar process and upload the files or directory tree as independent files. Note that if the artifact is a directory, the artifact driver must support the ability to save/load the directory appropriately.
//
// swagger:model io.argoproj.workflow.v1alpha1.NoneStrategy
type IoArgoprojWorkflowV1alpha1NoneStrategy interface{}
