// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoArgoprojWorkflowV1alpha1EventResponse io argoproj workflow v1alpha1 event response
//
// swagger:model io.argoproj.workflow.v1alpha1.EventResponse
type IoArgoprojWorkflowV1alpha1EventResponse interface{}
