// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

// IoK8sApimachineryPkgApisMetaV1Fields Fields stores a set of fields in a data structure like a Trie. To understand how this is used, see: https://github.com/kubernetes-sigs/structured-merge-diff
//
// swagger:model io.k8s.apimachinery.pkg.apis.meta.v1.Fields
type IoK8sApimachineryPkgApisMetaV1Fields interface{}
