// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// IoK8sAPICoreV1WindowsSecurityContextOptions WindowsSecurityContextOptions contain Windows-specific options and credentials.
//
// swagger:model io.k8s.api.core.v1.WindowsSecurityContextOptions
type IoK8sAPICoreV1WindowsSecurityContextOptions struct {

	// GMSACredentialSpec is where the GMSA admission webhook (https://github.com/kubernetes-sigs/windows-gmsa) inlines the contents of the GMSA credential spec named by the GMSACredentialSpecName field. This field is alpha-level and is only honored by servers that enable the WindowsGMSA feature flag.
	GmsaCredentialSpec string `json:"gmsaCredentialSpec,omitempty"`

	// GMSACredentialSpecName is the name of the GMSA credential spec to use. This field is alpha-level and is only honored by servers that enable the WindowsGMSA feature flag.
	GmsaCredentialSpecName string `json:"gmsaCredentialSpecName,omitempty"`
}

// Validate validates this io k8s api core v1 windows security context options
func (m *IoK8sAPICoreV1WindowsSecurityContextOptions) Validate(formats strfmt.Registry) error {
	return nil
}

// ContextValidate validates this io k8s api core v1 windows security context options based on context it is used
func (m *IoK8sAPICoreV1WindowsSecurityContextOptions) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *IoK8sAPICoreV1WindowsSecurityContextOptions) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *IoK8sAPICoreV1WindowsSecurityContextOptions) UnmarshalBinary(b []byte) error {
	var res IoK8sAPICoreV1WindowsSecurityContextOptions
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
